// src/views/Settings.vue
<template>
  <Navigations>
    <template #accessory>
      <IconButton icon="Back" />
      <div>Settings</div>
    </template>
    <IconButton icon="Help" href="https://revolicon.com/help" />
  </Navigations>
  <div class="content">
    <SimpleBar data-simplebar-auto-hide="false">
      <Section icon="size" title="Size"></Section>
      <Section icon="frame" title="Frame"></Section>
      <Color />
      <Section icon="finder" title="Finder"></Section>
      <Section icon="quickactions" title="Quick actions"></Section>
      <Section icon="appearance" title="Appearance"></Section>
      <Section title="Other">
        <Button full @click="removeBetaKey">Logout</Button>
        <Button variant="destructive" full @click="removeAllData">
          <template v-if="!sure">Reset All Settings</template>
          <template v-else>Are You Sure</template>
        </Button>
      </Section>
    </SimpleBar>
  </div>
</template>

<script setup>
  import { ref } from 'vue'
  import { SimpleBar } from 'simplebar-vue3'

  import { $post } from '@/utils/message'

  import Button, { IconButton } from '@/components/Button'

  import Navigations from '@/components/Navigations.vue'
  import Section from '@/components/Settings/Section.vue'
  import Color from '@/components/Settings/Color'

  const sure = ref(false)

  const removeBetaKey = () => $post('settings/removeData', 'betaKey')
  const removeAllData = () => {
    if (sure.value) $post('settings/removeAllData')
    sure.value = !sure.value
  }
</script>

// src/pages/Settings/index.tsx
import React from "react"
import SimpleBar from "simplebar-react"

import styles from "./styles.module.scss"

import { useNavigate } from "react-router-dom"

import Button, { IconButton } from "@/components/Button"
import Navigations, { Accessory } from "@/components/Navigations"

import { postMessage } from "@/utils/message"
import Section from "@/pages/Settings/Section"

const Settings: React.FC = () => {
  const navigate = useNavigate()
  const logout = () => {
    postMessage("settings/removeData", "betaKey")
    navigate("/", { replace: true })
  }

  return (
    <div className={styles.settings}>
      <Navigations>
        <Accessory>
          <IconButton icon="back" onClick={() => navigate("/")} />
          <div>Settings</div>
        </Accessory>
        <IconButton icon="help" href="https://revolicon.com/help" />
      </Navigations>
      <SimpleBar className={styles.settings__content}>
        <Section title="Size" icon="size">
          d
        </Section>
        <Section title="Frame" icon="frame">
          d
        </Section>
        <Section title="Color" icon="color">
          d
        </Section>
        <Section title="Finder" icon="finder">
          d
        </Section>
        <Section title="Quick actions" icon="quickactions">
          d
        </Section>
        <Section title="Appearance" icon="appearance">
          d
        </Section>
        <Section title="Other" icon="">
          <Button
            full={true}
            variant="primary"
            onClick={() => navigate("/test")}
          >
            Test Page
          </Button>
          <Button full={true} variant="destructive" onClick={() => logout()}>
            Logout
          </Button>
        </Section>
      </SimpleBar>
    </div>
  )
}

export default Settings
