// src/pages/Finder/index.tsx
import React from "react"

import styles from "./styles.module.scss"

import { useNavigate } from "react-router-dom"

import { Tab, Tabs } from "@/components/Tabs"
import { IconButton } from "@/components/Button"

import Navigations from "@/components/Navigations"

const Finder: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className={styles.finder}>
      <Navigations>
        <Tabs>
          <Tab active={true}>Icons</Tab>
          <Tab>Categories</Tab>
        </Tabs>
        <IconButton icon="adjust" onClick={() => navigate("/settings")} />
      </Navigations>
    </div>
  )
}

export default Finder

// src/views/Finder.vue
<template>
  <Navigations>
    <template #accessory>
      <Tabs :options="tabs">
        <Tab value="icons">Icons</Tab>
        <Tab value="categories">Categories</Tab>
      </Tabs>
    </template>
    <IconButton icon="Adjust" @click="router.push({ name: 'settings' })" />
  </Navigations>
  <KeepAlive>
    <component :is="tabsComponent[tabs.active]" />
  </KeepAlive>
</template>

<script setup>
  import { reactive } from 'vue'
  import { useRouter } from 'vue-router'

  import { IconButton } from '@/components/Button'
  import { Tabs, Tab } from '@/components/Tabs'

  import Navigations from '@/components/Navigations.vue'
  import Icons from '@/views/Finder/Icons.vue'
  import Categories from '@/views/Finder/Categories.vue'

  const router = useRouter()

  const tabs = reactive({
    active: 'icons',
  })
  const tabsComponent = {
    icons: Icons,
    categories: Categories,
  }
</script>
